apiVersion: apps/v1
kind: Deployment
metadata:
  name: mybrick-backend
  namespace: production
  labels:
    app: mybrick-backend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
  selector:
    matchLabels:
      app: mybrick-backend
  template:
    metadata:
      labels:
        app: mybrick-backend
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: mybrick-backend
          image: mikedeni/mybrick-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5154
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: ConnectionString
            - name: Jwt__Key
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: Jwt__Key
            - name: ASPNETCORE_URLS
              value: "http://+:5154"
          readinessProbe:
            httpGet:
              path: /metrics
              port: 5154
            initialDelaySeconds: 3
            periodSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /metrics
              port: 5154
            initialDelaySeconds: 20
            periodSeconds: 15
