apiVersion: apps/v1
kind: Deployment
metadata:
  name: mybrick-frontend
  namespace: production
  labels:
    app: mybrick-frontend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
  selector:
    matchLabels:
      app: mybrick-frontend
  template:
    metadata:
      labels:
        app: mybrick-frontend
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: mybrick-frontend
          image: mikedeni/mybrick-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 1
            periodSeconds: 2
            failureThreshold: 2
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 15
