{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "app-secrets",
    "namespace": "production"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "app-secrets",
        "namespace": "production"
      }
    },
    "encryptedData": {
      "ConnectionString": "AgBWNJ6OBd17d2j+WMLl31sTQBDhQvoh+WsBe8mJaQl1KPma7hFu/Y+FTFL0EL0jOksz5yCckAhx4ia55zLWnmdwpB2DHp27CdOcQtsCaoAp5kcPwNT3ts1ur1YR4p9hmyo+241Jj5+/7Rl+E8K9xeA0ps8xaAr61rzfrx+o/6xo8F34T0zqtZUdL33nodZxonh/DGR2/La+MnV2/QK4GrLM6w5fcB84sKZUuAxFV6yKHyMmyQFR8B8QPkmrD486DpFRU1VDWLcJP2iCZgEw11Bp2tr2AmaMPQHZi3o/u1mzQIzuhNKlYCf6yKaG1mMGysBgn+DQA9OPnCHaO6bPlYQ1EYzvswI8nxX5/DQz/fy+58vj5NrF5wlKy3fxb4aHLohZM+uDi++X8nyR9WaEJZnxL0Sq0LAIGelg+p0hKCfjzCbMzyoTQXKJNE5U8cqcKK2v8qhVGcE81l/gT7zHqtbrwGkhgLPpiF46/mr5JipEPxpumUaMp2t6JfS0HCUOtpEVhCHguE/QQ1lC4WhYQluV1XrL/SHbLWIk8+fXH5vqPkpgJDbOWr5dZVAGklb5i3Ep++eMPiyRjVe/2D/lspiruvsGncfpW5ZCuX+6oEU2VsPvtGxEkQqI49rYklAZkOPhgXEZoJ5Z2767/voDT+R9chedwxceqfuJI57LuVIooX286JPxFBniDvuIdmGJjXmEO7KH0lCHHDz+Imf3012z6AjyadgjuF1qaQwmlTqg8xrsJCCnheVbGTbPmh1LdrUSTX1A2vah/JyTA1xG11/4O6KrZsSTbL1gljSWPHrEz3uBE6m3d6E=",
      "Jwt__Key": "AgBvIeOFxdmNwS29pFngWFqKAf5wJpkmPb52Ujwf5yNDII6DK8a9zz9tQahvREnnGPCjNGQbSq8b3My7B2mQTsWp9QBG17N3MqE33aHBlvgdAKkbiQ0tpbKDFeSH7kxyF3+vocRqlIQYTL5nPAuS7Cj8iH7r5o6cq2wwmhDYM+/zraL5IPeJNphW21eFCQ+sVLWzp8OJpzJCWJ+rniI6fFkxRyb7pZYqe2dWkY1aybzx9MOCohd+1rMs6FsyuAv++4dLPHYrfVt1V+OcvPSftKLgwkadL8Z1NXImJq3gtWjSSIOX7x1SN0EvMMujUyjWDsRBmM219/8IclwURbkCvPA8Buyoynpg10n6i+dxbDVUNaASjP/jOiu8W7ROdnOzKYH0lb/DvBxMJUYE7VBAzT9TP9SrRrrCfpMbhWmqtxWNThvEEnKGSv0o/dGQf9Yh8OXL52dpbfxA6VHYUI2LzNWUloj0aEjwJhmQxS3Ryk0DWCA+mTa97sx5QPwzgciyzrFd/qX5PzyRsaCHWlH/9Jk96iZDw6xfChtFV12s6rlR+hCvYFA7z50hqMQLdjROwJmO+zk6ecFsfhNouwKGumMTcwC2hL9JvcePYIiMjlh3ir9PtGKPlnOMNXKLeixa8nYf94+v4szu7Bnn5wolXZWZ5bGzGUlmGw99KkNVqAJo3B+BhK4l9aeGlZ2RkV3yWJIkDwiwZgMQeooWsKGVKP9oamUoAcNiM7ogVEQGcbKoigpmVot9jfJaC4sLL+Xqme4Zj4Yl752PZ8EQeA=="
    }
  }
}
